---
- name: check for supported operating system on target
  fail:
    msg: "the operating system of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: ( ansible_distribution|lower != "ubuntu" )

- name: include distro specific tasks
  include_tasks: "{{ ansible_distribution|lower }}.yml"
  when: ( sudoers is defined ) or
        ( sudoers_d is defined )
